build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/raymond880824/wwdrupal 
    - docker build -t registry.gitlab.com/raymond880824/wwdrupal .
    - docker run registry.gitlab.com/raymond880824/wwdrupal /script/to/run/tests
    - docker push registry.gitlab.com/raymond880824/wwdrupal:latest
  only:
    - master

